apiVersion: v1
kind: Service
metadata:
  name: agentos-model-policy
  labels:
    app: agentos-model-policy
spec:
  selector:
    app: agentos-model-policy
  ports:
    - name: http
      port: 50082
      targetPort: 8082
